version: '2'
services:
# === Postgres database ===
  postgres-db:
    build:
      context: ./postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
# === itinerary ===
  itinerary:
    build:
      context: ./
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
